### PR TITLE
Adding westfall-young p-value adjustment for multiple tests

### PR DESCRIPTION
**Pull request by marcandre259**
From closed pr #698

Takes in most of @s3alfisc review comments. 
Tests are still a weak point. 
Possible issue with Randomization Inference -> #717

### CODE REVIEW

**Comment by marcandre259** [comment]
pre-commit.ci autofix

**Comment by s3alfisc** [comment]
Thanks @marcandre259 , I'll review this evening!

**Comment by s3alfisc** [comment]
Hi, this looks very good, thank you @marcandre259! I left a tiny comment that I fixed myself =) I might also add some unit tests tomorrow and think again about the issue of RI vs the bootstrap you raised in the other PR. What is your current thinking on this at the moment? Do you think it is a bug, or are we being fooled by statistics?

**Comment by marcandre259** [comment]
> Hi, this looks very good, thank you @marcandre259! I left a tiny comment that I fixed myself =) I might also add some unit tests tomorrow and think again about the issue of RI vs the bootstrap you raised in the other PR. What is your current thinking on this at the moment? Do you think it is a bug, or are we being fooled by statistics? 

Thanks for looking into it @s3alfisc :) I can also add tests if needed. 

Regarding the (maybe) issue, for me what is weird is getting this super tight null distribution. I figure maybe I'm missing something. In any case, there are probably tons of randomization sampling programs out there to do comparisons, so if it's still hanging, I'll look into it this weekend.

**Comment by s3alfisc** [comment]
Thanks for tackling the tests! 

But the null distribution seems to fit the analytical SEs? The tests against [ritest ](https://github.com/grantmcdermott/ritest)are [here](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_ritest.py), though I only check p-values as far as I recall, not null distribution widths.

**Comment by s3alfisc** [comment]
Actually there are tests for the SEs of the ritest t-stats and the lower bound of its ci implemented as well: https://github.com/py-econometrics/pyfixest/blob/ce4efd370710bf2a75b66815f3f614cbe4946fbf/tests/test_ritest.py#L104 Though if you have access to a Stata license, would of course be great to check against Stata ritest as well!

**Comment by s3alfisc** [comment]
Now that I've found the ritest bug and fixed it in #730, I will take another look at this & implement some tests tomorrow evening. 👍

**Comment by s3alfisc** [comment]
pre-commit.ci autofix

**Review by s3alfisc — APPROVED** [review]

**Comment by s3alfisc** [comment]
And merged. Thanks so much @marcandre259!

**Pull request merged**
