### PR TITLE
Add and adjust benchmark notebook with linearmodels (absorbingls) + adding solver argument and integration tests to fepois and feols

### PR DESCRIPTION
**Pull request by marcandre259**
Regarding #558, I also tried including fastreg but encountered issues getting it through the benchmarks (might have just been a speed issue on my computer, and can have a look back). 

AbsorbingLS took super long on the larger rows quantities, and apparently didn't give a solution on the largest one (ran through the night, so I assume it has a max number of iterations). 

Regarding #550, beginner friendly issue, and it's on the backlog for a little while, so I also attempt to tackle it in this request. I compare the regression coefficients in the integration test.

### CODE REVIEW

**Comment by s3alfisc** [comment]
Super cool, thanks so much @marcandre259! I'll review this later today =)

**Comment by s3alfisc** [comment]
@all-contributors please add @marcandre259 for code

**Comment by s3alfisc** [comment]
@pre-commit ci autofix

**Comment by s3alfisc** [comment]
pre-commit.ci autofix

**Comment by s3alfisc** [comment]
Some of the tests for the solvers seem to fail for Poisson Regression - I suppose that due to the iterative nature of the solver, exact equality might be a too strict criterion. Maybe we should lower the testing threshold? Maybe we could work with `np.testing.assert_allclose()` and work with a tolerance in the 1e-12 range?

**Comment by s3alfisc** [comment]
Btw, how did setting up the env and installing all dependencies with pixi work for you? Was it relatively smooth or did you experience some hiccups?

**Comment by marcandre259** [comment]
Thank you for looking at the pull request @s3alfisc :)

> Some of the tests for the solvers seem to fail for Poisson Regression - I suppose that due to the iterative nature of the solver, exact equality might be a too strict criterion. Maybe we should lower the testing threshold? Maybe we could work with `np.testing.assert_allclose()` and work with a tolerance in the 1e-12 range?

I can look adding the assert (and checking a bit what is going on in the back-end) this week. 

> Btw, how did setting up the env and installing all dependencies with pixi work for you? Was it relatively smooth or did you experience some hiccups

The initial set-up went fine, but I experienced some hiccups when running the tests. Namely, I needed to install some R dependencies, but the R version 4.3.* (I think), was not recent enough for the dependencies. I don't know how do environment management in R (installing older versions of packages for exemple), and got stuck there. 

I also use the vscode debugger extensively, and did not figure out how to use pixi with it yet, so I've been working in a conda environment and then switching to pixi to run the test basically.

**Comment by s3alfisc** [comment]
> I can look adding the assert (and checking a bit what is going on in the back-end) this week.

Sounds good, thank you! I a quite convinced that the test criterion is simply a bit too strict =) 

> The initial set-up went fine, but I experienced some hiccups when running the tests. Namely, I needed to install some R dependencies, but the R version 4.3.* (I think), was not recent enough for the dependencies. I don't know how do environment management in R (installing older versions of packages for exemple), and got stuck there.

Cool, I think that is super valuable feedback! I think I should start to manage all R dependencies via conda (where possible) and split the test set into core tests (i.e. tests that we'd like to run every time and for which all dependencies can be managed via conda) and advanced tests (for which the R packages might not be available through conda). I guess users should not need to install the ritest package from r-universe just to run some very basic tests on pyfixest 😄

**Comment by marcandre259** [comment]
pre-commit.ci autofix

**Comment by s3alfisc** [comment]
Perfect, thank you @marcandre259!

**Comment by saidamir** [comment]
@s3alfisc sorry for not completing the ticket, I was pretty swamped during the last few months (still job hunting) and I actually tried completing the ticket, but encountered few problems with git and also realized that quite few changes happened to the overall design of the library and while I didn't complete the ticket, I still spent quite some time on it. As a beginner, I still have to spend significant time on issues. Hopefully, I will be able to close other tickets.

**Comment by s3alfisc** [comment]
Hi @saidamir , no worries at all, and thanks for all your efforts so far =) Would you be interested to pick up another ticket?

**Comment by saidamir** [comment]
Yes, sure, however, I am still interviewing now, so I can work on it possible at the end of November. Is this okay with you?






On Saturday 26 October 2024 at 05:50:00 GMT-4, Alexander Fischer ***@***.***> wrote: 







Hi @saidamir , no worries at all, and thanks for all your efforts so far =) Would you be interested to pick up another ticket?

**Pull request merged**
