### PR TITLE
Improve Panelview Function

### PR DESCRIPTION
**Pull request by rafimikail**
What: 
- Fix panelview plot in documentation
- Enable dynamic plot colors for panelview when collapse_by_cohort = True

### CODE REVIEW

**Comment by rafimikail** [comment]
Tested on docs-preview
**Before**
image

**After**
image

**Comment by rafimikail** [comment]
Hi @s3alfisc, this MR is to fix the bug on panelview plot size, as well as minor improvement to enable dynamic colors of pre and post treatment when setting collapse_to_cohort = True

I have ran the lint test locally and shows passed, not sure why the pre-commit workflow failed, need your help to review this, Thanks!

**Comment by s3alfisc** [comment]
pre-commit.ci autofix

**Comment by s3alfisc** [comment]
> I have ran the lint test locally and shows passed, not sure why the pre-commit workflow failed, is this expected? Need your help to review this, Thanks!

Also not sure why this sometimes happens ... currently running the ci bot, I hope it will fix it =)

**Review by s3alfisc — APPROVED** [review]

**Comment by s3alfisc** [comment]
Looks good now, thanks a ton @rafimikail!

**Pull request merged**
