### PR TITLE
Infra: added the release-drafter for automation of release notes

### LINKED ISSUE #491: Infra: Automate Publication of Release Notes on Github and Changelog
## Context

Currently, whenever a new version is released, I need to tag a new release on github "by hand" as well as update the [changelog ](https://py-econometrics.github.io/pyfixest/reference/) in the docs. There must be tools / gh actions out there to automate that procedure?

## To do

- Research the best tools.
- Adjust the github action workflow to automatically publish new release notes, and potentially, to automatically update the changelog. 
- Optimally, we would be able to cluster the content of the release notes by "new features", "breaking changes", "maintenance", "documentation", and "infrastructure".

### PR DESCRIPTION
**Pull request by sanskriti2005**
Added two files:
1) .github/workflows : added the release-drafter.yml file
2) .github : added the release-config.yml file (contains the format for the release notes)

closes #491

### CODE REVIEW

**Comment by s3alfisc** [comment]
Awesome, I'll do a proper review tonight after work =)

**Review by s3alfisc — APPROVED** [review]
Looks great, thank you @sanskriti2005! Congrats to your first PR to PyFixest =) 

@all-contributors please add @sanskriti2005 for infra

**Comment by s3alfisc** [comment]
@all-contributors please add @sanskriti2005 for infra

**Comment by s3alfisc** [comment]
Hey, it worked! 🎉 https://github.com/py-econometrics/pyfixest/releases It's really cool and will save me quite a bit of time going forward.

Please let me know if you'd be interested to keep contributing, and if yes, which topics would be particularly interesting for you @sanskriti2005 =)

**Comment by sanskriti2005** [comment]
@s3alfisc 
I'm glad this is of help! I would love to work on more issues. I'm currently not very particular about the things I work on, as I'm interested in learning about them.

**Pull request merged**
