### PR TITLE
Run more tests

### PR DESCRIPTION
**Pull request by s3alfisc**
- Bring back tests I un-commented a while back.
- Fix bug in `first_stage()` method with special `formulaic` syntax.
- Fix bug with `resid()` method, which sometimes would return **weighted** residuals. Now it always returns the **unweighted** residuals. 
- Add tests for `predict()`, `resid()` methods and `iwls_weights` attributes.

### CODE REVIEW

**Comment by Jayhyung** [comment]
Ah, I didn't notice that the IV part in `test_vs_fixest.py` was commented. I have worked on the seperate testing script(`test_iv.py`), so the diagnostic part of IV should work fine. If this indeed affects the parts I had worked on, please let me know!

**Comment by s3alfisc** [comment]
> Ah, I didn't notice that the IV part in test_vs_fixest.py was commented. 

Yeah, me neither; a seemingly innocuuous "skip" statement and I asked pytest to skip all IV tests 🤦‍♂️Yeah, generally I agree that all is fine - coefs, SEs etc are all correct. I think something broke with `C()` operators - maybe best to change this in a separate PR from this one here and the testing PR? I might ask you to review it at some point this week if that's ok =)

**Comment by s3alfisc** [comment]
Hi @Jayhyung , I pushed the changes to the IV module in [d7a792c](https://github.com/py-econometrics/pyfixest/pull/603/commits/d7a792cc46c8757d5b0670b64e2488cc761c6073), could you take a look in case you find some time (only at the specific commit)?

**Comment by Jayhyung** [comment]
Hi @s3alfisc ! I will check on this issue as soon as possible, possibly this weekend.

**Comment by s3alfisc** [comment]
Very cool! I think reviewing the IV parts should not take you more than 15 minutes =)

**Comment by s3alfisc** [comment]
Hi @Jayhyung, I will likely merge this in a few hours as I need this in another PR. If you find the time, would nevertheless be great if you'd review the IV part (we can always revert / update in case something is off / you think smth should be improved).

**Comment by Jayhyung** [comment]
Thanks for the reminder, @s3alfisc ! Please, proceed out my review at this moment. Sorry, I will take a look at some point today at evening, as I was swamped by my stuffs ;). If i find something weird or does not not work, I will make a new issue or PR.

**Comment by s3alfisc** [comment]
Sounds good and no worries at all!

**Pull request merged**
